const API=window.location.origin.replace(/\/$/,''),$=id=>document.getElementById(id);
let csrf='',mode='',idx=0,data={};
const M=[['sleep_duration','How long did you sleep?','Pick the window that feels closest.',[['\u25d4','Under 5h',4.5],['\u25d1','5\u20136h',5.5],['\u25d2','6\u20137h',6.5],['\u25d5','7\u20138h',7.5],['\u25c9','8\u20139h',8.5],['\u2726','9h+',9.5]]],['sleep_quality','How did your sleep feel?','No scorekeeping. Just your read.',[['\u2639','Rough',2],['\u25d4','Restless',4],['\u25d1','Okay',6],['\u25d5','Good',8],['\u263a','Deep',10]]],['energy','How are you arriving today?','First instinct.',[['\ud83d\udd0b','Drained',2],['\u25d4','Low',4],['\u25d1','Steady',6],['\u25d5','Good',8],['\u26a1','Charged',10]]],['morning_context','Anything unusual?','Optional. You can always skip.',[['\u25cb','Nothing unusual','none'],['\u25cc','Headache','headache'],['\u2301','Fatigue','fatigue'],['\u25b3','Pain','pain'],['\u2192','Skip','skipped']]]];
const E=[['mood','How was today?','The overall texture of the day.',[['\u2639','Low',2],['\u25d4','Heavy',4],['\u25d1','Mixed',6],['\u25d5','Good',8],['\u263a','Great',10]]],['stress','Where was your stress?','Today\u2019s signal, not a diagnosis.',[['\u25cb','Very low',1],['\u25d4','Low',3],['\u25d1','Moderate',5],['\u25d5','High',7],['\u25cf','Very high',9]]],['focus','How was your focus?','How easy was it to stay with things?',[['\u2601','Scattered',2],['\u25d4','Patchy',4],['\u25d1','Okay',6],['\u25d5','Strong',8],['\u25ce','Locked in',10]]],['activity_level','How much did you move?','Minutes can come later.',[['\u25cb','Very little','very_little'],['\u25d4','Light','light'],['\u25d1','Moderate','moderate'],['\u25d5','A lot','high'],['\u2192','Skip','skipped']]],['diet_quality','How did you eat?','Think balance, not calories.',[['\u00b7','Chaotic','low'],['\u25d4','Mostly quick','fair'],['\u25d1','Mixed','mixed'],['\u25d5','Mostly balanced','good'],['\u2726','Very balanced','high']]],['caffeine','Caffeine today?','Coffee, tea and energy drinks count.',[['\u25cb','None',0],['\u25d4','1','1'],['\u25d1','2','2'],['\u25d5','3+','3']]],['alcohol','Alcohol today?','Optional, no judgement.',[['\u25cb','None',0],['\u25d4','1','1'],['\u25d1','2','2'],['\u25d5','3+','3']]],['nicotine','Nicotine / smoking?','Optional context for your baseline.',[['\u25cb','None','none'],['\u25d4','Some','some'],['\u25d5','Frequent','frequent']]]];
function node(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function clear(n){while(n.firstChild)n.removeChild(n.firstChild)}
function setMsg(id,text){$(id).textContent=text}
async function account(){if(csrf){const r=await fetch(API+'/api/v1/auth/logout',{method:'POST',headers:{'X-CSRF-Token':csrf}});if(r.ok){csrf='';$('account').textContent='SIGN IN';location.reload()}}else $('auth').classList.toggle('hide')}
async function authCall(path){const email=$('email').value.trim().toLowerCase(),password=$('password').value;if(!email||password.length<12||!/[a-z]/.test(password)||!/[A-Z]/.test(password)||!/[0-9]/.test(password)||!/[^A-Za-z0-9]/.test(password)){setMsg('authmsg','Enter a valid email and a 12+ character password with upper, lower, number and symbol.');return}setMsg('authmsg','');try{const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});let d={};try{d=await r.json()}catch{}if(!r.ok){setMsg('authmsg',d.detail||'Could not authenticate.');return}await fetch(API+'/api/v1/auth/csrf');csrf=document.cookie.split('; ').find(x=>x.startsWith('nexgene_csrf='))?.split('=')[1]||'';$('auth').classList.add('hide');$('account').textContent='SIGN OUT';await loadProfile();await load()}catch(e){setMsg('authmsg','NexGene could not reach the server. Open this app from the NexGene address shown in the README.')}}
function register(){authCall('/api/v1/auth/register')}function login(){authCall('/api/v1/auth/login')}
async function loadProfile(){const d=await get('/api/v1/profile');if(!d.complete){$('onboarding').classList.remove('hide');const p=d.profile||{};['age_range','country','occupation','study_field','schedule','timezone'].forEach(k=>{if($(k))$(k).value=p[k]||''});if($('student'))$('student').value=p.student===true?'yes':p.student===false?'no':''}else $('onboarding').classList.add('hide')}
async function saveProfile(){const payload={age_range:$('age_range').value.trim()||null,country:$('country').value.trim()||null,occupation:$('occupation').value.trim()||null,student:$('student').value===''?null:$('student').value==='yes',study_field:$('study_field').value.trim()||null,schedule:$('schedule').value||null,timezone:$('timezone').value.trim()||null};try{const r=await fetch(API+'/api/v1/profile',{method:'PUT',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok){setMsg('profilemsg',d.detail||'Could not save your context.');return}$('onboarding').classList.add('hide');setMsg('profilemsg','');await loadReport()}catch(e){setMsg('profilemsg','Could not save your context right now.')}}
function start(m){if(!csrf){$('auth').classList.remove('hide');setMsg('authmsg','Create an account first. Your check-ins need somewhere private to live.');return}mode=m;idx=0;data={};$('sheet').classList.remove('hide');render()}
function render(){const arr=mode==='morning'?M:E,item=arr[idx];$('step').textContent=`${idx+1} / ${arr.length}`;const q=$('q');clear(q);q.append(node('div','k',`${mode} check-in`),node('h3',null,item[1]),node('p',null,item[2]));const choices=$('choices');clear(choices);item[3].forEach(o=>{const b=node('button','choice'),i=node('i',null,o[0]),label=node('b',null,o[1]);b.append(i,label);b.onclick=()=>{choices.querySelectorAll('.choice').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');data[item[0]]=o[2];$('next').disabled=false};choices.appendChild(b)});$('next').disabled=data[item[0]]===undefined;$('next').textContent=idx===arr.length-1?'SAVE':'CONTINUE'}
async function nextStep(){const arr=mode==='morning'?M:E;if(idx<arr.length-1){idx++;render();return}const r=await fetch(`${API}/api/v1/checkins/${mode}`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({values:data})});if(!r.ok){alert('Could not save this check-in.');return}closeSheet();await load()}
function closeSheet(){$('sheet').classList.add('hide')}
async function get(p){if(!csrf)return{};const r=await fetch(API+p);if(r.status===401){csrf='';$('account').textContent='SIGN IN';$('auth').classList.remove('hide');setMsg('authmsg','Your session expired. Please sign in again.');return{}}return r.ok?r.json():{}}
function showView(v){['today','patterns','timeline','report'].forEach(x=>{$(x+'View').classList.toggle('hide',x!==v);const n=$('n'+x[0].toUpperCase()+x.slice(1));if(n)n.classList.toggle('active',x===v)});if(v==='patterns')loadPatterns();if(v==='timeline')loadTimeline();if(v==='report')loadReport()}
async function loadSignals(){const d=await get('/api/v1/signals'),box=$('signals');clear(box);(d.signals||[]).forEach((sig,i)=>{const card=node('div','signal');card.append(node('small',null,i===0?'NEXGENE SIGNAL':'\u25cc SIGNAL'),node('b',null,sig.title),node('span',null,sig.body));if(sig.action==='check_in'){const b=node('button',null,'CHECK IN');b.onclick=()=>start(new Date().getHours()<15?'morning':'evening');card.appendChild(b)}else if(sig.action==='patterns'){const b=node('button',null,'SEE PATTERNS');b.onclick=()=>showView('patterns');card.appendChild(b)}box.appendChild(card)});if(!box.firstChild)box.append(node('div','empty','The Raven is watching quietly.'))}
async function load(){if(!csrf)return;const d=await get('/api/v1/today');const keys=[['sleep_duration','SLEEP',v=>v+'h'],['energy','ENERGY',v=>v+'/10'],['mood','MOOD',v=>v+'/10'],['stress','STRESS',v=>v+'/10'],['focus','FOCUS',v=>v+'/10'],['diet_quality','EATING',v=>v]];const snapshot=$('snapshot');clear(snapshot);let count=0;keys.forEach(x=>{if(d[x[0]]!==undefined){count++;const m=node('div','metric');m.append(node('small',null,x[1]),node('b',null,x[2](d[x[0]])));snapshot.appendChild(m)}});if(!snapshot.firstChild){const e=node('div','empty');e.append(node('b',null,'A quiet page.'),node('span',null,'Two tiny check-ins begin the picture.'));snapshot.appendChild(e)}$('count').textContent=`${Math.min(count,2)} / 2 check-ins`;$('bar').style.width=Math.min(count,2)*50+'%';const ins=await get('/api/v1/insights');$('insight').textContent=ins.items?.[0]||'Your baseline is beginning to take shape.';$('account').textContent='SIGN OUT';await loadSignals()}
async function loadPatterns(){const d=await get('/api/v1/patterns'),cards=$('patternCards');clear(cards);const labels=[['sleep_duration','Sleep','h'],['sleep_quality','Sleep quality','/10'],['energy','Energy','/10'],['stress','Stress','/10'],['focus','Focus','/10']];labels.forEach(([k,l,u])=>{if(d.averages?.[k]!==undefined){const p=node('div','pattern');p.append(node('small',null,l),node('b',null,d.averages[k]+u),node('span',null,'30 day average'));cards.appendChild(p)}});if(!cards.firstChild){const e=node('div','empty');e.append(node('b',null,'Still gathering signal.'),node('span',null,'Keep checking in and the pattern view will wake up.'));cards.appendChild(e)}const chart=$('chart');clear(chart);(d.series||[]).slice(-14).forEach(p=>{const day=node('div','day'),bars=node('div','bars'),sleep=node('i'),focus=node('i');sleep.style.height=((p.sleep_duration||0)/10*100)+'%';focus.style.height=((p.focus||0)/10*100)+'%';bars.append(sleep,focus);day.append(bars,node('small',null,p.date.slice(5)));chart.appendChild(day)});if(!chart.firstChild)chart.append(node('div','empty','No chart yet.'))}
async function loadTimeline(){const rows=await get('/api/v1/timeline'),timeline=$('timeline');clear(timeline);rows.slice(0,60).forEach(r=>{const e=node('div','event');e.append(node('span',null,new Date(r.recorded_at).toLocaleDateString()),node('b',null,r.kind.replaceAll('_',' ')),node('em',null,String(r.value)));timeline.appendChild(e)});if(!timeline.firstChild){const e=node('div','empty');e.append(node('b',null,'No observations yet.'),node('span',null,'Your first check-in will appear here.'));timeline.appendChild(e)}}
async function loadReport(){const d=await get('/api/v1/reports/weekly'),box=$('reportContent');if(!box)return;clear(box);if(d.status==='not_ready'){box.append(node('div','reportHero',d.message));return}const hero=node('div','reportHero');hero.append(node('div','eyebrow',d.coverage?.days+' DAYS OF SIGNAL'),node('h2',null,d.title||'Your week with NexGene'),node('p',null,d.subtitle||''));box.appendChild(hero);if(d.profile?.occupation||d.profile?.student!==null&&d.profile?.student!==undefined){const context=node('div','reportContext');let label=d.profile.occupation||'Student';if(d.profile.student===true&&d.profile.study_field)label+=' \u00b7 '+d.profile.study_field;context.append(node('small',null,'YOUR CONTEXT'),node('b',null,label));box.appendChild(context)}(d.sections||[]).forEach(sec=>{const card=node('article','reportCard');card.append(node('small',null,sec.kind?.toUpperCase()||'NOTE'),node('h3',null,sec.title),node('p',null,sec.body));box.appendChild(card)});const ex=node('article','reportCard experiment');ex.append(node('small',null,'ONE THING TO TRY'),node('h3',null,'Next week'),node('p',null,d.experiment||'Keep the signal coming.'));box.appendChild(ex);const note=node('p','reportNote',d.disclaimer||'');box.appendChild(note)}
async function boot(){const d=new Date();$('date').textContent=d.toLocaleDateString(undefined,{day:'2-digit',month:'short'}).toUpperCase();$('greeting').textContent=d.getHours()<12?'Good morning.':d.getHours()<18?'Good afternoon.':'Good evening.';if(document.cookie.includes('nexgene_csrf=')){await fetch(API+'/api/v1/auth/csrf');csrf=document.cookie.split('; ').find(x=>x.startsWith('nexgene_csrf='))?.split('=')[1]||'';$('account').textContent='SIGN OUT';const me=await get('/api/v1/auth/me');if(me.id){await loadProfile();await load()}else csrf=''}}boot();
